### ISSUE TITLE
Unsupported newer version: 4

### ISSUE THREAD

**Issue by miraks31** [hleofxquotes/mnyjson#1]
Hi,

I'm the main developer of Skrooge and I use SUNRIISE to be able to import mny file in Skrooge easily.
This works well! Thank you for job.
A user send me a mny file not working.
Indeed, when I launch sunriize on the file, I get this:
```
ava -jar /home/s/Telechargements/sunriise-export-0.0.1-SNAPSHOT-exec.jar export.json "/home/s/Bureau/DiachunKeyBUToday.mny" /tmp/{81c05ed4-a47d-4586-b0a8-20bed1d5be31}

0 [main] INFO  com.hungle.sunriise.export.ExportToJSONDirCmd.export(ExportToJSONDirCmd.java:52) - dbFile=/home/s/Bureau/DiachunKeyBUToday.mny
5 [main] INFO  com.hungle.sunriise.export.ExportToJSONDirCmd.export(ExportToJSONDirCmd.java:53) - outDir=/tmp/{81c05ed4-a47d-4586-b0a8-20bed1d5be31}
10 [main] INFO  com.hungle.sunriise.export.AbstractExportToJSON.initThreadPool(AbstractExportToJSON.java:228) - ThreadPool is NOT enable.
17 [main] INFO  com.hungle.sunriise.io.MnyDb.openDb(MnyDb.java:405) - # Opening dbFile=/home/s/Bureau/DiachunKeyBUToday.mny, readOnly=true, encrypted=true
93 [main] ERROR com.hungle.sunriise.export.ExportToJSONDirCmd.export(ExportToJSONDirCmd.java:67) - java.io.IOException: Unsupported newer version: 4
java.io.IOException: Unsupported newer version: 4
        at com.healthmarketscience.jackcess.impl.JetFormat.getFormat(JetFormat.java:308)
        at com.healthmarketscience.jackcess.impl.DatabaseImpl.<init>(DatabaseImpl.java:518)
        at com.healthmarketscience.jackcess.impl.DatabaseImpl.open(DatabaseImpl.java:401)
        at com.healthmarketscience.jackcess.DatabaseBuilder.open(DatabaseBuilder.java:252)
        at com.hungle.sunriise.io.MnyDb.openDb(MnyDb.java:444)
        at com.hungle.sunriise.io.MnyDb.openDb(MnyDb.java:387)
        at com.hungle.sunriise.io.MnyDb.openDb(MnyDb.java:316)
        at com.hungle.sunriise.io.MnyDb.openDb(MnyDb.java:339)
        at com.hungle.sunriise.io.MnyDb.<init>(MnyDb.java:100)
        at com.hungle.sunriise.export.AbstractExportToJSON.export(AbstractExportToJSON.java:204)
        at com.hungle.sunriise.export.ExportToJSONDirCmd.export(ExportToJSONDirCmd.java:65)
        at com.hungle.sunriise.export.ExportToJSONCmd.main(ExportToJSONCmd.java:77)
        at app.ExportToJSON.main(ExportToJSON.java:15)
        at app.ModuleExportMain.main(ModuleExportMain.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
99 [main] INFO  com.hungle.sunriise.export.ExportToJSONDirCmd.export(ExportToJSONDirCmd.java:69) - < DONE

```

Do you know? Is it a bug ? What should I do to be able to get json data from this mny file?

Thank you in advance for your help.
Regards.

**Comment by miraks31** [comment]
More information coming from the user: 

> My mny fiile was made by an old MSMoney program which was made for Windows 95.  I have used it both on Windows XP and in a Wine program on Linux.

Regards.
